# Generated by Django 4.2.14 on 2025-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idautor', models.AutoField(db_column='idAutor', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('nomemeio', models.CharField(db_column='nomeMeio', max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('ideditora', models.AutoField(db_column='idEditora', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.IntegerField(db_comment='somente n·meros')),
                ('telefone', models.IntegerField(db_comment='somente n·meros')),
                ('email', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'editora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntidadeProprietaria',
            fields=[
                ('identidade', models.AutoField(db_column='idEntidade', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.IntegerField(db_comment='somente n·meros')),
                ('telefone', models.IntegerField(db_comment='somente n·meros')),
                ('numero', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'entidade_proprietaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('idexemplar', models.AutoField(db_column='idExemplar', primary_key=True, serialize=False)),
                ('tombo', models.IntegerField()),
                ('exemplar', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'exemplar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneroObra',
            fields=[
                ('idgenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'genero_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('idlivro', models.AutoField(db_column='idLivro', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('volume', models.IntegerField()),
                ('edicao', models.IntegerField()),
                ('isbn', models.IntegerField(db_comment='somente n·meors')),
            ],
            options={
                'db_table': 'livro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoObra',
            fields=[
                ('idtipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_obra',
                'managed': False,
            },
        ),
    ]
