# Generated by Django 4.2.14 on 2025-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('idbairro', models.AutoField(db_column='idBairro', primary_key=True, serialize=False)),
                ('bairro', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bairro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('idcidade', models.AutoField(db_column='idCidade', primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('idlogradouro', models.AutoField(db_column='idLogradouro', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Rua', 'Rua'), ('Avenida', 'Avenida'), ('Praça', 'Praca'), ('Rodovia', 'Rodovia'), ('Travessas', 'Travessas'), ('Alameda', 'Alameda'), ('Vila', 'Vila')], max_length=50)),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'logradouro',
                'managed': False,
            },
        ),
    ]
