# Generated by Django 4.2.14 on 2025-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('datanascimento', models.DateField(db_column='dataNascimento')),
                ('cpf', models.IntegerField(db_comment='somente n·meros')),
                ('telefone', models.IntegerField(db_comment='somente n·meros')),
                ('email', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
