# Generated by Django 4.2.14 on 2025-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atraso',
            fields=[
                ('idatraso', models.AutoField(db_column='idAtraso', primary_key=True, serialize=False)),
                ('valormulta', models.DecimalField(db_column='valorMulta', decimal_places=0, max_digits=10)),
                ('status', models.CharField(max_length=6)),
                ('datadevolucaoprevista', models.DateField(db_column='dataDevolucaoPrevista')),
            ],
            options={
                'db_table': 'atraso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('idemprestimo', models.AutoField(db_column='idEmprestimo', primary_key=True, serialize=False)),
                ('dataemprestimo', models.DateField(db_column='dataEmprestimo')),
                ('datadevolucaoprevista', models.DateField(db_column='dataDevolucaoPrevista')),
                ('datadevolucao', models.DateField(db_column='dataDevolucao')),
                ('status', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'emprestimo',
                'managed': False,
            },
        ),
    ]
