# Generated by Django 4.2.14 on 2025-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atraso',
        ),
    ]
